# This Dockerfile sets up the Dev Environment
FROM mcr.microsoft.com/devcontainers/base:alpine-3.20

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.9.2 /uv /uvx /bin/

# Set working directory
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

# Set the target location for the virtual environment to a non-mounted path
ENV UV_PROJECT_ENVIRONMENT="../.venv"
ENV PATH="../.venv/bin:$PATH"

# Copy dependency files and install dependencies
COPY pyproject.toml /app/
COPY uv.lock /app/
RUN uv sync --locked

# Copy rest of source code
COPY . .

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application; gets overridden in docker-compose.yaml
CMD ["uv", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]