services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.dev # Dev Dockerfile
      # dockerfile: Dockerfile.prod # Production Dockerfile
    command: sleep infinity
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis-db

  redis-db:
    image: redis:latest
    volumes:
      - redis-data:/data

volumes:
  redis-data: